name: End-to-end MGS workflow test sharded

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  test:
    runs-on: ubuntu-latest
      strategy:
        matrix:
          shard: [1, 2, 3, 4]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Nextflow latest-edge
        uses: nf-core/setup-nextflow@v3
        with:
          version: "latest-edge"

      - name: Install nf-test
        run: |
          wget -qO- https://get.nf-test.com | bash
          sudo mv nf-test /usr/local/bin/

      - name: Run Run Tests (Shard ${{ matrix.shard }}/${{ strategy.job-total }})
        run: nf-test test --tag "End-to-end test of MGS workflow" --shard ${{ matrix.shard }}/${{ strategy.job-total }}
