name: End-to-end MGS workflow test

on: [pull_request]

jobs:
  test-index:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Nextflow latest (stable)
        uses: nf-core/setup-nextflow@v1
        with:
          version: "latest"

      - name: Install nf-test
        run: |
          wget -qO- https://get.nf-test.com | bash
          sudo mv nf-test /usr/local/bin/

      - name: Run index workflow
        run: nf-test test --tag index --verbose
  test-run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Nextflow latest (stable)
        uses: nf-core/setup-nextflow@v1
        with:
          version: "latest"

      - name: Install nf-test
        run: |
          wget -qO- https://get.nf-test.com | bash
          sudo mv nf-test /usr/local/bin/

      - name: Run run workflow
        run: nf-test test --tag run --verbose

      - name: Run run_dev_se workflow
        run: nf-test test --tag run_dev_se --verbose

  test-validation:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Nextflow latest (stable)
        uses: nf-core/setup-nextflow@v1
        with:
          version: "latest"

      - name: Install nf-test
        run: |
          wget -qO- https://get.nf-test.com | bash
          sudo mv nf-test /usr/local/bin/

      - name: Run run_validation workflow
        run: nf-test test --tag validation --verbose