name: End-to-end MGS workflow test

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  test-index:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Nextflow latest (stable)
        uses: nf-core/setup-nextflow@v1
        with:
          version: "latest"

      - name: Install nf-test
        run: |
          wget -qO- https://get.nf-test.com | bash
          sudo mv nf-test /usr/local/bin/

      - name: Run index workflow
        run: nf-test test --tag index --verbose
  test-run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Nextflow latest (stable)
        uses: nf-core/setup-nextflow@v1
        with:
          version: "latest"

      - name: Install nf-test
        run: |
          wget -qO- https://get.nf-test.com | bash
          sudo mv nf-test /usr/local/bin/

      - name: Run run workflow
        run: nf-test test --tag run --verbose

  test-run-output:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Nextflow latest (stable)
        uses: nf-core/setup-nextflow@v1
        with:
          version: "latest"

      - name: Install nf-test
        run: |
          wget -qO- https://get.nf-test.com | bash
          sudo mv nf-test /usr/local/bin/

      - name: Run run workflow
        run: nf-test test --tag run_output --verbose --ci

  test-validation:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Nextflow latest (stable)
        uses: nf-core/setup-nextflow@v1
        with:
          version: "latest"

      - name: Install nf-test
        run: |
          wget -qO- https://get.nf-test.com | bash
          sudo mv nf-test /usr/local/bin/

      - name: Run run_validation workflow
        run: nf-test test --tag validation --verbose

  test-downstream:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Nextflow latest (stable)
        uses: nf-core/setup-nextflow@v1
        with:
          version: "latest"

      - name: Install nf-test
        run: |
          wget -qO- https://get.nf-test.com | bash
          sudo mv nf-test /usr/local/bin/

      - name: Run DOWNSTREAM workflow
        run: nf-test test --tag downstream --verbose

  test-downstream-output:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Nextflow latest (stable)
        uses: nf-core/setup-nextflow@v1
        with:
          version: "latest"

      - name: Install nf-test
        run: |
          wget -qO- https://get.nf-test.com | bash
          sudo mv nf-test /usr/local/bin/

      - name: Run DOWNSTREAM workflow and check output
        run: nf-test test --tag downstream_output --verbose --ci
