name: End-to-end MGS workflow test

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Nextflow latest-edge
        uses: nf-core/setup-nextflow@v1
        with:
          version: "latest-edge"

      - name: Install nf-test
        run: |
          wget -qO- https://get.nf-test.com | bash
          sudo mv nf-test /usr/local/bin/

      - name: Run index workflow
        run: nf-test test --tag index --verbose

      - name: Clean docker for more space
        run: |
          docker kill $(docker ps -q) 2>/dev/null || true
          docker rm $(docker ps -a -q) 2>/dev/null || true
          docker rmi $(docker images -q) -f 2>/dev/null || true
          docker system prune -af --volumes

      - name: Clean up nf-test dir
        run: sudo rm -rf .nf-test

      - name: Run run workflow
        run: nf-test test --tag run --verbose
