name: End-to-end MGS workflow test for single-end run

on: [pull_request]

jobs:
  test-run-dev-se:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Nextflow latest (stable)
        uses: nf-core/setup-nextflow@v1
        with:
          version: "latest"

      - name: Install nf-test
        run: |
          wget -qO- https://get.nf-test.com | bash
          sudo mv nf-test /usr/local/bin/

      - name: Run run_dev_se workflow on single-end data
        run: nf-test test --tag run_dev_se --verbose

      - name: Run run_dev_se workflow on ONT data
        run: nf-test test --tag run_dev_se_ont --verbose